Task 1 (summ)
js-tasks-ru/jsbasic-20220211_dmitriy619 pull request #1
Opened 2022-02-09 19:42 UTC by Dimmaster87

2022-02-09 19:42 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @SinimaWath должен запустить тесты.

2022-02-11 18:29 UTC, SinimaWath requested changes

2022-02-11 18:29 UTC, SinimaWath commented on 0-module/1-task/index.js
> +  return sum;
Нет необходимости в промежуточном sum: `return m + n`;

2022-02-11 18:29 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  var result = 1;
Давай не использовать var :) Устаревшая коснтрукция, здесь тебе подойдет `let`

2022-02-11 18:35 UTC, Dimmaster87 commented on 1-module/1-task/index.js
> +  var result = 1;
в циклах также?

2022-02-12 10:17 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  var result = 1;
Да

2022-02-12 10:34 UTC, Dimmaster87 commented on 1-module/1-task/index.js
> +  var result = 1;
Все правки в дальнейших коммитах

2022-02-12 10:37 UTC, Dimmaster87 commented on 1-module/1-task/index.js
> +  var result = 1;
Там же и след задачи

2022-02-13 15:49 UTC, SinimaWath approved these changes
все ок

2022-02-13 15:49 UTC, merged